import {useEffect,useMemo,useState} from "react";
import {MODEL_CATALOG_SCHEMA,type ApiErrorResponse,type ApiModelCatalogResponse,type ApiModelId} from "@senfate/contracts";
import {clearModelSettings,loadModelSettings,modelOverrideCount,overridesFromValues,saveModelSettings,valuesWithOverrides} from "../model-settings";

const API_BASE=import.meta.env.PUBLIC_API_BASE??"https://fyapeng.com/senfate/api/v1";
const groupLabels={dynamic:"动态生命周期",pattern:"月令格局",climate:"调候坐标",balancing:"平衡决策",topics:"主题贡献"} as const;
const domainLabels:Readonly<Record<string,string>>={career:"事业",family:"家庭",general:"总体",health:"身心",mobility:"迁动",personality:"表达",relationship:"关系",risk:"风险",study:"学习",wealth:"财务"};
const groupDescriptions={dynamic:"改变原局、大运与流年进入动态状态时的相对质量。",pattern:"控制月令本气在格局候选排序中的作用。",climate:"控制寒热与燥湿坐标进入调候投影的强度。",balancing:"控制强弱和调候坐标合成为五行平衡向量的权重。",topics:"只缩放已由古籍条件激活的主题贡献，不改变规则条件。"} as const;
function visibleLabel(path:string,label:string):string{const domain=path.split(".").at(-1);return path.startsWith("topics.")?`主题权重 · ${domainLabels[domain??""]??domain}`:label}

export function ModelConfigurator(){
  const[catalog,setCatalog]=useState<ApiModelCatalogResponse>();const[selected,setSelected]=useState<ApiModelId>("transparent-baseline");const[group,setGroup]=useState<keyof typeof groupLabels>("dynamic");const[values,setValues]=useState<Record<string,number>>({});const[message,setMessage]=useState("正在读取模型合同…");
  useEffect(()=>{const controller=new AbortController();void(async()=>{try{const response=await fetch(`${API_BASE}/models`,{signal:controller.signal});const body=await response.json() as ApiModelCatalogResponse|ApiErrorResponse;if(!response.ok||body.schemaVersion!==MODEL_CATALOG_SCHEMA||!("presets" in body))throw new Error("模型参数目录暂时不可用");const stored=loadModelSettings();const preset=body.presets.find(item=>item.id===(stored?.baseModelId??"transparent-baseline"))??body.presets[0];if(!preset)throw new Error("模型预设为空");setCatalog(body);setSelected(preset.id);setValues(stored?valuesWithOverrides(preset.values,stored.overrides):{...preset.values});setMessage(stored&&modelOverrideCount(stored.overrides)>0?`已载入 ${modelOverrideCount(stored.overrides)} 项本地自定义参数。`:"所有参数均来自公开模型合同。")}catch(cause){if(!controller.signal.aborted)setMessage(cause instanceof Error?cause.message:"模型参数目录暂时不可用")}})();return()=>controller.abort()},[]);
  const preset=useMemo(()=>catalog?.presets.find(item=>item.id===selected),[catalog,selected]);const parameters=useMemo(()=>catalog?.parameters.filter(item=>item.group===group)??[],[catalog,group]);const overrides=useMemo(()=>preset?overridesFromValues(preset.values,values):{},[preset,values]);const count=modelOverrideCount(overrides);
  function choose(id:ApiModelId){const next=catalog?.presets.find(item=>item.id===id);if(!next)return;setSelected(id);setValues({...next.values});setMessage(`已切换到${next.label}，尚未保存。`)}
  function save(returnToAnalysis=false){if(!preset)return;saveModelSettings({schema:"senfate-web-model-settings.v1",baseModelId:selected,overrides});setMessage(count?`已保存 ${count} 项自定义参数；下一次排盘会完整重算。`:"已保存当前预设，未附加自定义参数。");if(returnToAnalysis)window.location.assign("/senfate/")}
  function reset(){if(!preset)return;setValues({...preset.values});clearModelSettings();setMessage("已恢复当前预设并清除本地自定义参数。")}
  function exportJson(){if(!preset)return;const payload={schema:"senfate-public-model-configuration.v1",baseModelId:selected,overrides};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));const anchor=document.createElement("a");anchor.href=url;anchor.download=`senfate-model-${selected}.json`;anchor.click();URL.revokeObjectURL(url);setMessage("配置 JSON 已导出。")}
  return <div className="configurator live-configurator"><aside className="preset-panel"><div className="panel-heading"><div><span className="step-label">MODEL PRESETS</span><h2>模型预设</h2></div><span className="version-pill">v0.4</span></div>{catalog?.presets.map(item=><button type="button" className={selected===item.id?"selected":""} onClick={()=>choose(item.id)} key={item.id}><i></i><span><strong>{item.label}</strong><small>{item.id==="month-command"?"提高月令与格局结构作用":item.id==="climate-priority"?"提高寒热燥湿与调候作用":"均衡保留各计算阶段"}</small></span></button>)}<div className="preset-note"><span>配置边界</span><p>公开配置只允许调整列出的有限权重。干支、十神、关系候选和古籍条件本身不可通过参数改写。</p></div></aside><section className="parameter-panel"><div className="parameter-header"><div><span>当前配置</span><h2>{preset?.label??"模型目录"}</h2><p>{count?`${count} 项参数偏离预设，保存后将写入计算证书。`:"当前数值与预设一致。"}</p></div><div><button type="button" onClick={exportJson} disabled={!preset}>导出 JSON</button><button type="button" className="dark" onClick={()=>save(true)} disabled={!preset}>应用到排盘</button></div></div><div className="parameter-tabs">{(Object.keys(groupLabels) as (keyof typeof groupLabels)[]).map(key=><button type="button" className={group===key?"active":""} onClick={()=>setGroup(key)} key={key}>{groupLabels[key]}</button>)}</div><p className="parameter-group-copy">{groupDescriptions[group]}</p><div className="parameter-list">{parameters.map(item=>{const label=visibleLabel(item.path,item.label);const update=(value:number)=>setValues(current=>({...current,[item.path]:value}));return <label key={item.path}><div><strong>{label}</strong><small>{item.path} · {item.minimum}—{item.maximum}</small></div><input aria-label={`${label}滑杆`} type="range" min={item.minimum} max={item.maximum} step={item.step} value={values[item.path]??0} onChange={event=>update(Number(event.target.value))}/><input className="parameter-number" aria-label={`${label}数值`} type="number" min={item.minimum} max={item.maximum} step={item.step} value={values[item.path]??0} onChange={event=>update(Number(event.target.value))}/></label>})}</div><div className="config-footer"><div><span>配置状态</span><code>{message}</code></div><p><button type="button" onClick={()=>save(false)} disabled={!preset}>仅保存</button><button type="button" onClick={reset} disabled={!preset}>恢复预设</button></p></div></section></div>;
}
