import { describe,expect,it } from "vitest";
import { baziMonthPillar,compileBaziCalendar,equationOfTimeMinutes,type CalendarProfile } from "./calendar";

const profile:CalendarProfile={id:"transparent-baseline",version:"0.1.0",useApparentSolarTime:true,dayBoundary:"zi-initial",luckDirection:"yang-male-yin-female-forward",daysPerLuckYear:3};
describe("calendar engine",()=>{
  it("keeps equation-of-time output in a physical range",()=>{expect(Math.abs(equationOfTimeMinutes(Date.UTC(2000,0,1)))).toBeLessThan(20)});
  it("derives all twelve flow-month pillars from the certified Bazi year",()=>{expect(baziMonthPillar(2000,0)).toMatchObject({stem:"戊",branch:"寅"});expect(baziMonthPillar(2000,11)).toMatchObject({stem:"己",branch:"丑"})});
  it("compiles pillars from a certified solar-term window",()=>{const result=compileBaziCalendar({year:2000,month:2,day:10,hour:12,minute:0,utcOffsetMinutes:480,longitudeDegrees:120,latitudeDegrees:31.2},profile,{ephemerisId:"fixture",ephemerisVersion:"1",baziYear:2000,monthOrdinal:0,previousJieUtcMs:Date.UTC(2000,1,4),nextJieUtcMs:Date.UTC(2000,2,5)},"male",2);expect(result.ok).toBe(true);if(result.ok){expect(result.value.pillars.year).toMatchObject({stem:"庚",branch:"辰"});expect(result.value.pillars.month).toMatchObject({stem:"戊",branch:"寅"});expect(result.value.pillars.hour.branch).toBe("午");expect(new Date(result.value.normalizedTime.apparentSolarWallTimeMs).getUTCHours()).toBe(11);expect(result.value.majorLuck).toHaveLength(2);expect(result.value.direction).toBe("forward")}});
  it("fails closed when uncertainty crosses a jie boundary",()=>{const boundary=Date.UTC(2000,1,4,0);const result=compileBaziCalendar({year:2000,month:2,day:4,hour:8,minute:0,utcOffsetMinutes:480,longitudeDegrees:120,latitudeDegrees:31.2,clockUncertaintySeconds:5},profile,{ephemerisId:"fixture",ephemerisVersion:"1",baziYear:2000,monthOrdinal:0,previousJieUtcMs:boundary,nextJieUtcMs:Date.UTC(2000,2,5)},"male");expect(result).toMatchObject({ok:false,code:"ephemeris-window-mismatch"})});
  it("propagates term uncertainty into a luck-start interval",()=>{const result=compileBaziCalendar({year:2000,month:2,day:10,hour:12,minute:0,utcOffsetMinutes:480,longitudeDegrees:120,latitudeDegrees:31.2,clockUncertaintySeconds:10},profile,{ephemerisId:"fixture",ephemerisVersion:"1",baziYear:2000,monthOrdinal:0,previousJieUtcMs:Date.UTC(2000,1,4),nextJieUtcMs:Date.UTC(2000,2,5),nextJieUncertaintySeconds:120},"male",1);expect(result.ok).toBe(true);if(!result.ok)return;expect(result.value.luckStartAgeInterval.lower).toBeLessThan(result.value.luckStartAgeYears);expect(result.value.luckStartAgeInterval.upper).toBeGreaterThan(result.value.luckStartAgeYears);expect(result.value.majorLuck[0]!.startUtcInterval.upper).toBeGreaterThan(result.value.majorLuck[0]!.startUtcMs)});
});
