import type { ClosedResult } from "./algebra";
import type { CivilBirthInput } from "./calendar";
import moment from "moment-timezone";

export interface ZonedCivilBirthInput {readonly year:number;readonly month:number;readonly day:number;readonly hour:number;readonly minute:number;readonly second?:number;readonly timeZone:string;readonly longitudeDegrees:number;readonly latitudeDegrees:number;readonly disambiguation?:"earlier"|"later"|"reject";readonly clockUncertaintySeconds?:number;readonly coordinateUncertaintyMeters?:number}
export interface TimeZoneCandidate {readonly utcMs:number;readonly offsetMinutes:number;readonly offsetSeconds:number}
export interface ResolvedZonedBirth {readonly civilBirth:CivilBirthInput;readonly selected:TimeZoneCandidate;readonly candidates:readonly TimeZoneCandidate[];readonly timeZone:string}
export type TimeZoneFailure="invalid-local-time"|"invalid-time-zone"|"nonexistent-local-time"|"ambiguous-local-time";

function validGregorian(input:ZonedCivilBirthInput):boolean{const test=new Date(Date.UTC(input.year,input.month-1,input.day,input.hour,input.minute,input.second??0));return test.getUTCFullYear()===input.year&&test.getUTCMonth()===input.month-1&&test.getUTCDate()===input.day&&test.getUTCHours()===input.hour&&test.getUTCMinutes()===input.minute&&test.getUTCSeconds()===(input.second??0)}

export const TZDB_VERSION=`IANA-${moment.tz.dataVersion}`;
export const TIME_ZONE_PROVIDER=`moment-timezone@${moment.tz.version}`;

export function resolveZonedCivilBirth(input:ZonedCivilBirthInput):ClosedResult<ResolvedZonedBirth,TimeZoneFailure>{const certificate={functional:"calendar.time-zone-resolution",provider:TIME_ZONE_PROVIDER,tzdbVersion:TZDB_VERSION,timeZone:input.timeZone,disambiguation:input.disambiguation??"reject"};if(!validGregorian(input))return{ok:false,code:"invalid-local-time",reason:"Local civil fields do not form a Gregorian date-time",certificate};const zone=moment.tz.zone(input.timeZone);if(!zone)return{ok:false,code:"invalid-time-zone",reason:"Time-zone identifier is absent from the pinned IANA database",certificate};const wallMs=Date.UTC(...([input.year,input.month-1,input.day,input.hour,input.minute,input.second??0] as [number,number,number,number,number,number]));const offsetsWestMinutes=new Set(zone.offsets);const candidates=[...offsetsWestMinutes].map(offsetWestMinutes=>{const utcMs=wallMs+Math.round(offsetWestMinutes*60_000);const offsetSeconds=-offsetWestMinutes*60;return{utcMs,offsetMinutes:offsetSeconds/60,offsetSeconds}}).filter(candidate=>Math.round(candidate.utcMs-zone.utcOffset(candidate.utcMs)*60_000)===wallMs).filter((candidate,index,array)=>array.findIndex(other=>other.utcMs===candidate.utcMs)===index).sort((a,b)=>a.utcMs-b.utcMs);if(candidates.length===0)return{ok:false,code:"nonexistent-local-time",reason:"The local clock time did not exist because of a civil-time transition",certificate:{...certificate,offsetsExaminedSeconds:[...offsetsWestMinutes].map(offset=>-offset*60)}};if(candidates.length>1&&(input.disambiguation===undefined||input.disambiguation==="reject"))return{ok:false,code:"ambiguous-local-time",reason:"The local clock time occurred more than once; choose earlier or later",certificate:{...certificate,candidates}};const selected=input.disambiguation==="later"?candidates[candidates.length-1]!:candidates[0]!;const civilBirth:CivilBirthInput={year:input.year,month:input.month,day:input.day,hour:input.hour,minute:input.minute,second:input.second??0,utcOffsetMinutes:selected.offsetMinutes,longitudeDegrees:input.longitudeDegrees,latitudeDegrees:input.latitudeDegrees,clockUncertaintySeconds:input.clockUncertaintySeconds??0,coordinateUncertaintyMeters:input.coordinateUncertaintyMeters??0};return{ok:true,value:{civilBirth,selected,candidates,timeZone:input.timeZone},certificate:{...certificate,candidates,selected}}}
