import type { ClosedResult } from "./algebra";
import type { CivilBirthInput } from "./calendar";

export interface ZonedCivilBirthInput {readonly year:number;readonly month:number;readonly day:number;readonly hour:number;readonly minute:number;readonly second?:number;readonly timeZone:string;readonly longitudeDegrees:number;readonly latitudeDegrees:number;readonly disambiguation?:"earlier"|"later"|"reject";readonly clockUncertaintySeconds?:number;readonly coordinateUncertaintyMeters?:number}
export interface TimeZoneCandidate {readonly utcMs:number;readonly offsetMinutes:number;readonly offsetSeconds:number}
export interface ResolvedZonedBirth {readonly civilBirth:CivilBirthInput;readonly selected:TimeZoneCandidate;readonly candidates:readonly TimeZoneCandidate[];readonly timeZone:string}
export type TimeZoneFailure="invalid-local-time"|"invalid-time-zone"|"nonexistent-local-time"|"ambiguous-local-time";

function formatter(timeZone:string):Intl.DateTimeFormat{return new Intl.DateTimeFormat("en-CA-u-ca-iso8601-nu-latn",{timeZone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"})}
function fieldsAt(format:Intl.DateTimeFormat,utcMs:number):readonly number[]{const values:Record<string,number>={};for(const part of format.formatToParts(new Date(utcMs)))if(["year","month","day","hour","minute","second"].includes(part.type))values[part.type]=Number(part.value);return[values.year!,values.month!,values.day!,values.hour!,values.minute!,values.second!]}
function sameFields(a:readonly number[],b:readonly number[]):boolean{return a.length===b.length&&a.every((value,index)=>value===b[index])}
function validGregorian(input:ZonedCivilBirthInput):boolean{const test=new Date(Date.UTC(input.year,input.month-1,input.day,input.hour,input.minute,input.second??0));return test.getUTCFullYear()===input.year&&test.getUTCMonth()===input.month-1&&test.getUTCDate()===input.day&&test.getUTCHours()===input.hour&&test.getUTCMinutes()===input.minute&&test.getUTCSeconds()===(input.second??0)}

export function resolveZonedCivilBirth(input:ZonedCivilBirthInput,tzdbVersion:string):ClosedResult<ResolvedZonedBirth,TimeZoneFailure>{const certificate={functional:"calendar.time-zone-resolution",provider:"Intl.DateTimeFormat",tzdbVersion,timeZone:input.timeZone,disambiguation:input.disambiguation??"reject"};if(!validGregorian(input))return{ok:false,code:"invalid-local-time",reason:"Local civil fields do not form a Gregorian date-time",certificate};let format:Intl.DateTimeFormat;try{format=formatter(input.timeZone);format.format(new Date(0))}catch{return{ok:false,code:"invalid-time-zone",reason:"Time-zone identifier is not recognized by this runtime",certificate}}const target=[input.year,input.month,input.day,input.hour,input.minute,input.second??0];const wallMs=Date.UTC(...([input.year,input.month-1,input.day,input.hour,input.minute,input.second??0] as [number,number,number,number,number,number]));const offsets=new Set<number>();for(let delta=-48;delta<=48;delta+=3){const instant=wallMs+delta*3_600_000;const local=fieldsAt(format,instant);const localMs=Date.UTC(local[0]!,local[1]!-1,local[2]!,local[3]!,local[4]!,local[5]!);offsets.add(Math.round((localMs-instant)/1000))}const candidates=[...offsets].map(offsetSeconds=>({utcMs:wallMs-offsetSeconds*1000,offsetMinutes:offsetSeconds/60,offsetSeconds})).filter(candidate=>sameFields(fieldsAt(format,candidate.utcMs),target)).sort((a,b)=>a.utcMs-b.utcMs);if(candidates.length===0)return{ok:false,code:"nonexistent-local-time",reason:"The local clock time did not exist because of a civil-time transition",certificate:{...certificate,offsetsExaminedSeconds:[...offsets]}};if(candidates.length>1&&(input.disambiguation===undefined||input.disambiguation==="reject"))return{ok:false,code:"ambiguous-local-time",reason:"The local clock time occurred more than once; choose earlier or later",certificate:{...certificate,candidates}};const selected=input.disambiguation==="later"?candidates[candidates.length-1]!:candidates[0]!;const civilBirth:CivilBirthInput={year:input.year,month:input.month,day:input.day,hour:input.hour,minute:input.minute,second:input.second??0,utcOffsetMinutes:selected.offsetMinutes,longitudeDegrees:input.longitudeDegrees,latitudeDegrees:input.latitudeDegrees,clockUncertaintySeconds:input.clockUncertaintySeconds??0,coordinateUncertaintyMeters:input.coordinateUncertaintyMeters??0};return{ok:true,value:{civilBirth,selected,candidates,timeZone:input.timeZone},certificate:{...certificate,candidates,selected}}}
