import { finiteSignedMeasure,kleeneAnd,type FiniteSignedMeasure,type KleeneTruth } from "@senfate/core/algebra";
import type { SenFateModelProfile } from "@senfate/core/model";
import { BRANCH_DEFINITIONS,ELEMENTS,STEM_DEFINITIONS,tenGod } from "@senfate/core/ontology";
import type { ReferenceNormalFormPhaseResult } from "@senfate/core/resolution";
import type { CompiledReferenceRecord,NormalizedReferenceCondition } from "./compiler";

export type TopicDomain="career"|"family"|"general"|"health"|"mobility"|"personality"|"relationship"|"risk"|"study"|"wealth";
export const TOPIC_DOMAINS:readonly TopicDomain[]=["career","family","general","health","mobility","personality","relationship","risk","study","wealth"];
export type TopicEffectOperator="complete_or_transform"|"pressure"|"reveal"|"support"|"weaken_or_block";
export type TopicConditionOperator="branchFormation.equals"|"dayMasterState.equals"|"dayStem.equals"|"element.state"|"ganZhi.in"|"ganZhi.present"|"luckDirection.equals"|"monthBranch.equals"|"monthBranch.in"|"relation.exists"|"seasonalCommand"|"sex.equals"|"symbol.absent"|"symbol.present";
export interface ReferenceFeatureSnapshot {
  readonly schema:"senfate-resolved-reference-features.v1"; readonly phase:"natal"|"luck"|"annual";
  readonly dayStem:string; readonly monthBranch:string; readonly dayMasterState?:string; readonly luckDirection?:string; readonly sex?:string;
  readonly elementStates:Readonly<Record<string,string|undefined>>; readonly presentGanZhi:ReadonlySet<string>; readonly resolvedRelations:ReadonlySet<string>; readonly seasonalCommands:ReadonlySet<string>; readonly presentSymbols:ReadonlySet<string>; readonly abundantSymbols:ReadonlySet<string>;
}
export interface ActivatedEventEvidence { readonly operator:TopicEffectOperator; readonly domain:TopicDomain; readonly polarity:string }
export interface ActivatedReferenceCondition {readonly kind:NormalizedReferenceCondition["kind"];readonly operator:TopicConditionOperator;readonly value:string|readonly string[];readonly subject?:string}
export interface ActivatedReferenceSource { readonly recordId:string; readonly familyId:string; readonly bookId:string; readonly lineStart:number; readonly lineEnd:number; readonly scopes:readonly ("natal"|"luck"|"annual")[]; readonly conditions:readonly ActivatedReferenceCondition[]; readonly domains:readonly TopicDomain[]; readonly polarity:string; readonly eventEvidence:readonly ActivatedEventEvidence[] }
export interface TopicEventHypothesis {
  readonly schema:"senfate-topic-event-hypothesis.v3"; readonly predicateId:string; readonly phase:ReferenceFeatureSnapshot["phase"];
  readonly domain:TopicDomain; readonly operator:TopicEffectOperator; readonly direction:"support"|"pressure"|"mixed"|"neutral";
  readonly contribution:number; readonly magnitude:number; readonly sourceCount:number; readonly familyCount:number; readonly bookCount:number;
  readonly scopeEvidence:Readonly<{natalSources:number;luckSources:number;annualSources:number;unscopedSources:number}>;
  readonly evidenceStatus:"single-source"|"same-book-corroborated"|"cross-book-corroborated"|"mixed-evidence";
  readonly epistemicStatus:"traditional-model-hypothesis";
}
export interface ContributionCertificate {
  readonly schema:"senfate-topic-contribution-certificate.v5"; readonly phase:ReferenceFeatureSnapshot["phase"]; readonly model:string;
  readonly program:Readonly<{total:number;executable:number;deferred:number;contested:number;evidence:number;fixture:number}>;
  readonly evaluated:number; readonly activated:number; readonly inactive:number; readonly unresolved:number;
  readonly activatedFamilies:readonly string[]; readonly unresolvedFamilies:readonly string[]; readonly activatedSources:readonly ActivatedReferenceSource[];
  readonly contribution:FiniteSignedMeasure<TopicDomain>; readonly eventHypotheses:readonly TopicEventHypothesis[];
}

const RELATION_LABEL:Readonly<Record<string,string>>={"stem-combine":"合","branch-combine":"合","branch-clash":"冲","branch-harm":"害","branch-break":"破","branch-punishment":"刑","three-harmony":"三合","three-meeting":"三会"};
const GENERATES:Readonly<Record<string,string>>={木:"火",火:"土",土:"金",金:"水",水:"木"};
export function materializeResolvedReferenceFeatures(normal:ReferenceNormalFormPhaseResult,context:Readonly<{luckDirection?:string;sex?:string}>={}):ReferenceFeatureSnapshot{
  const state=normal.dynamicState;const atoms=state.elementMeasure.atoms;const mean=state.elementMeasure.total/ELEMENTS.length;const elementStates=Object.fromEntries(ELEMENTS.map(element=>[element,atoms[element]>=mean*1.25?"abundant":"deficient"]));const presentSymbols=new Set<string>();const presentGanZhi=new Set<string>();
  for(const item of state.pillars){presentSymbols.add(item.pillar.stem);presentSymbols.add(item.pillar.branch);presentGanZhi.add(`${item.pillar.stem}${item.pillar.branch}`);for(const hidden of BRANCH_DEFINITIONS[item.pillar.branch].hiddenStems)presentSymbols.add(hidden.stem);presentSymbols.add(tenGod(state.natal.day.stem,item.pillar.stem))}
  const active=normal.relations.filter(item=>item.status==="effective"||item.status==="transformed");const resolvedRelations=new Set(active.map(item=>RELATION_LABEL[item.candidate.kind]!).filter(Boolean));const seasonalCommands=new Set<string>();const monthElement=BRANCH_DEFINITIONS[state.natal.month.branch].element;const dayElement=STEM_DEFINITIONS[state.natal.day.stem].element;seasonalCommands.add(monthElement===dayElement||GENERATES[monthElement]===dayElement?"supported":"unsupported");for(const relation of active)if(relation.status==="transformed"&&relation.candidate.targetElement)seasonalCommands.add(`${relation.candidate.targetElement}局`);
  return{schema:"senfate-resolved-reference-features.v1",phase:normal.phase,dayStem:state.natal.day.stem,monthBranch:state.natal.month.branch,dayMasterState:state.strength.state,...(context.luckDirection?{luckDirection:context.luckDirection}:{}),...(context.sex?{sex:context.sex}:{}),elementStates,presentGanZhi,resolvedRelations,seasonalCommands,presentSymbols,abundantSymbols:new Set(ELEMENTS.filter(element=>elementStates[element]==="abundant"))};
}

function equality(actual:string|undefined,expected:unknown):KleeneTruth{if(actual===undefined)return"unknown";if(Array.isArray(expected))return expected.includes(actual)?"true":"false";return actual===expected?"true":"false"}
export function evaluateReferenceCondition(condition:NormalizedReferenceCondition,snapshot:ReferenceFeatureSnapshot):KleeneTruth{
  const expected=condition.value;
  switch(condition.operator){
    case"dayMasterState.equals":return equality(snapshot.dayMasterState,expected);case"dayStem.equals":return equality(snapshot.dayStem,expected);case"monthBranch.equals":return equality(snapshot.monthBranch,expected);case"monthBranch.in":return equality(snapshot.monthBranch,expected);case"luckDirection.equals":return equality(snapshot.luckDirection,expected);case"sex.equals":return equality(snapshot.sex,expected);
    case"element.state":return condition.subject?equality(snapshot.elementStates[condition.subject],expected):"unknown";
    case"ganZhi.present":return snapshot.presentGanZhi.has(String(expected))?"true":"false";case"ganZhi.in":return(Array.isArray(expected)?expected:[expected]).some(x=>snapshot.presentGanZhi.has(String(x)))?"true":"false";
    case"relation.exists":return snapshot.resolvedRelations.has(String(expected))?"true":"false";case"seasonalCommand":case"branchFormation.equals":return snapshot.seasonalCommands.has(String(expected))?"true":"false";
    case"symbol.present":return snapshot.presentSymbols.has(String(expected))?"true":"false";case"symbol.absent":return snapshot.presentSymbols.has(String(expected))?"false":"true";case"symbol.abundant":return snapshot.abundantSymbols.has(String(expected))?"true":"false";default:return"unknown";
  }
}

export function evaluateReferenceContributionSummary(records:readonly CompiledReferenceRecord[],snapshot:ReferenceFeatureSnapshot,model:SenFateModelProfile):Readonly<{contribution:FiniteSignedMeasure<TopicDomain>;activated:number}>{const contributions:Record<TopicDomain,number>={career:0,family:0,general:0,health:0,mobility:0,personality:0,relationship:0,risk:0,study:0,wealth:0};let activated=0;for(const record of records){const truth=kleeneAnd(record.conditions.map(condition=>evaluateReferenceCondition(condition,snapshot)));if(truth!=="true")continue;activated++;for(const effect of record.effects)for(const domain of effect.domains)if(TOPIC_DOMAINS.includes(domain as TopicDomain))contributions[domain as TopicDomain]+=polaritySign(effect.polarity)*(model.topics.domainWeights[domain]??0)}return{contribution:finiteSignedMeasure(TOPIC_DOMAINS,contributions),activated}}

function scopeApplies(record:CompiledReferenceRecord,phase:ReferenceFeatureSnapshot["phase"]):boolean {if(record.scopes.length===0)return true;if(record.scopes.includes("natal"))return true;if(phase==="luck"&&record.scopes.includes("luck"))return true;if(phase==="annual"&&(record.scopes.includes("luck")||record.scopes.includes("annual")))return true;return false}
function isTopicEffectOperator(value:string):value is TopicEffectOperator{return value==="complete_or_transform"||value==="pressure"||value==="reveal"||value==="support"||value==="weaken_or_block"}
function isTopicConditionOperator(value:string):value is TopicConditionOperator{return value==="branchFormation.equals"||value==="dayMasterState.equals"||value==="dayStem.equals"||value==="element.state"||value==="ganZhi.in"||value==="ganZhi.present"||value==="luckDirection.equals"||value==="monthBranch.equals"||value==="monthBranch.in"||value==="relation.exists"||value==="seasonalCommand"||value==="sex.equals"||value==="symbol.absent"||value==="symbol.present"}
function activatedConditions(record:CompiledReferenceRecord):readonly ActivatedReferenceCondition[]{return record.conditions.map(condition=>{if(!isTopicConditionOperator(condition.operator)||!(typeof condition.value==="string"||Array.isArray(condition.value)&&condition.value.every(value=>typeof value==="string")))throw new Error(`Executable reference condition escaped the closed topic contract: ${condition.operator}`);return{kind:condition.kind,operator:condition.operator,value:condition.value,...(condition.subject?{subject:condition.subject}:{})}})}
function polaritySign(polarity:string):number{return polarity==="support"?1:polarity==="pressure"?-1:0}
export function evaluateReferenceContributions(records:readonly CompiledReferenceRecord[],snapshot:ReferenceFeatureSnapshot,model:SenFateModelProfile):ContributionCertificate{
  const contributions:Record<TopicDomain,number>={career:0,family:0,general:0,health:0,mobility:0,personality:0,relationship:0,risk:0,study:0,wealth:0};const activatedFamilies:string[]=[];const unresolvedFamilies:string[]=[];const activatedSources:ActivatedReferenceSource[]=[];let evaluated=0;let inactive=0;
  const program={total:records.length,executable:0,deferred:0,contested:0,evidence:0,fixture:0};for(const record of records)program[record.disposition]++;
  for(const record of records){if(record.disposition!=="executable"||!scopeApplies(record,snapshot.phase))continue;evaluated++;const truth=kleeneAnd(record.conditions.map(condition=>evaluateReferenceCondition(condition,snapshot)));if(truth==="unknown"){unresolvedFamilies.push(record.familyId);continue}if(truth==="false"){inactive++;continue}activatedFamilies.push(record.familyId);const sourceDomains=new Set<TopicDomain>();const sourcePolarities=new Set<string>();const eventEvidence:ActivatedEventEvidence[]=[];for(const effect of record.effects){const domains=effect.domains.filter((domain):domain is TopicDomain=>TOPIC_DOMAINS.includes(domain as TopicDomain));for(const domain of domains){sourceDomains.add(domain);contributions[domain]+=polaritySign(effect.polarity)*(model.topics.domainWeights[domain]??0);if(isTopicEffectOperator(effect.operator))eventEvidence.push({operator:effect.operator,domain,polarity:effect.polarity})}sourcePolarities.add(effect.polarity)}activatedSources.push({recordId:record.recordId,familyId:record.familyId,bookId:record.bookId,lineStart:record.lineStart,lineEnd:record.lineEnd,scopes:record.scopes.filter((scope):scope is "natal"|"luck"|"annual"=>scope==="natal"||scope==="luck"||scope==="annual"),conditions:activatedConditions(record),domains:[...sourceDomains],polarity:sourcePolarities.size===1?[...sourcePolarities][0]!:"mixed",eventEvidence})}
  const groups=new Map<string,{domain:TopicDomain;operator:TopicEffectOperator;contribution:number;sources:Set<string>;families:Set<string>;books:Set<string>;polarities:Set<string>}>();
  for(const source of activatedSources)for(const evidence of source.eventEvidence){const key=`${evidence.domain}:${evidence.operator}`;let group=groups.get(key);if(!group){group={domain:evidence.domain,operator:evidence.operator,contribution:0,sources:new Set(),families:new Set(),books:new Set(),polarities:new Set()};groups.set(key,group)}group.contribution+=polaritySign(evidence.polarity)*(model.topics.domainWeights[evidence.domain]??0);group.sources.add(source.recordId);group.families.add(source.familyId);group.books.add(source.bookId);group.polarities.add(evidence.polarity)}
  const eventHypotheses:TopicEventHypothesis[]=[...groups.values()].map((group):TopicEventHypothesis=>{const conflict=group.polarities.has("support")&&group.polarities.has("pressure");const mixedDirection=conflict||group.polarities.has("mixed");const direction:TopicEventHypothesis["direction"]=group.contribution>0?"support":group.contribution<0?"pressure":mixedDirection?"mixed":"neutral";const evidenceStatus:TopicEventHypothesis["evidenceStatus"]=conflict?"mixed-evidence":group.books.size>1?"cross-book-corroborated":group.sources.size>1?"same-book-corroborated":"single-source";const sources=activatedSources.filter(source=>group.sources.has(source.recordId));const scopeEvidence={natalSources:sources.filter(source=>source.scopes.includes("natal")).length,luckSources:sources.filter(source=>source.scopes.includes("luck")).length,annualSources:sources.filter(source=>source.scopes.includes("annual")).length,unscopedSources:sources.filter(source=>source.scopes.length===0).length};return{schema:"senfate-topic-event-hypothesis.v3",predicateId:`${snapshot.phase}:${group.domain}:${group.operator}`,phase:snapshot.phase,domain:group.domain,operator:group.operator,direction,contribution:group.contribution,magnitude:Math.abs(group.contribution),sourceCount:group.sources.size,familyCount:group.families.size,bookCount:group.books.size,scopeEvidence,evidenceStatus,epistemicStatus:"traditional-model-hypothesis"}}).sort((a,b)=>Math.abs(b.contribution)-Math.abs(a.contribution)||a.predicateId.localeCompare(b.predicateId));
  return{schema:"senfate-topic-contribution-certificate.v5",phase:snapshot.phase,model:`${model.id}@${model.version}`,program,evaluated,activated:activatedFamilies.length,inactive,unresolved:unresolvedFamilies.length,activatedFamilies,unresolvedFamilies,activatedSources,contribution:finiteSignedMeasure(TOPIC_DOMAINS,contributions),eventHypotheses};
}
