import { fileURLToPath } from "node:url";
import { describe,expect,it } from "vitest";
import { TRANSPARENT_BASELINE_MODEL,sexagenary } from "@senfate/core";
import type { CompiledReferenceRecord } from "./compiler";
import { compileReferenceCorpus } from "./node";
import { ReferenceCalculationRuntime } from "./runtime";

function record(id:string,scope:string):CompiledReferenceRecord{return{recordId:id,bookId:"book",lineStart:1,lineEnd:1,familyId:id,ruleType:"prediction",sourceRole:"general_rule",scopes:[scope],conditions:[{kind:"day-stem",operator:"dayStem.equals",value:"戊"}],effects:[{operator:"support",domains:["career"],polarity:"support"}],terms:{},extractionConfidence:1,disposition:"executable",reason:"complete-canonical-rule"}}

describe("ReferenceCalculationRuntime",()=>{
  it("runs annual calculation through stable features and cumulative topic rules",()=>{const runtime=new ReferenceCalculationRuntime([record("n","natal"),record("l","luck"),record("a","annual")],TRANSPARENT_BASELINE_MODEL);const result=runtime.calculate({natal:{year:sexagenary(0),month:sexagenary(2),day:sexagenary(4),hour:sexagenary(6)},luck:sexagenary(10),annual:sexagenary(20),sex:"male",luckDirection:"forward"});expect(result.ok).toBe(true);if(!result.ok)return;expect(result.value.normalForm.status).toBe("stable");expect(result.value.topicCertificate.evaluated).toBe(3);expect(result.value.topicCertificate.contribution.atoms.career).toBe(3)});
  it("fails closed before topics when annual luck is missing",()=>{const runtime=new ReferenceCalculationRuntime([],TRANSPARENT_BASELINE_MODEL);expect(runtime.calculate({natal:{year:sexagenary(0),month:sexagenary(2),day:sexagenary(4),hour:sexagenary(6)},annual:sexagenary(20)})).toMatchObject({ok:false,code:"missing-luck-layer"})});
  it("keeps lightweight monthly trajectory contributions exactly equal to a full certificate",()=>{const runtime=new ReferenceCalculationRuntime([record("n","natal"),record("l","luck"),record("a","annual")],TRANSPARENT_BASELINE_MODEL);const input={natal:{year:sexagenary(0),month:sexagenary(2),day:sexagenary(4),hour:sexagenary(6)},luck:sexagenary(10),annual:sexagenary(20),month:sexagenary(30),sex:"male",luckDirection:"forward"} as const;const full=runtime.calculate(input),sample=runtime.calculateTrajectorySample(input);expect(full.ok).toBe(true);expect(sample.ok).toBe(true);if(!full.ok||!sample.ok)return;expect(sample.value.normalForm.fingerprint).toBe(full.value.normalForm.fingerprint);expect(sample.value.contribution).toEqual(full.value.topicCertificate.contribution)});
  it("evaluates the complete audited corpus without losing a disposition",()=>{const corpusPath=fileURLToPath(new URL("../../../data/classical-rules/classical-source-corpus.v4.0.json.gz",import.meta.url));const audit=compileReferenceCorpus(corpusPath);const result=new ReferenceCalculationRuntime(audit.records,TRANSPARENT_BASELINE_MODEL).calculate({natal:{year:sexagenary(16),month:sexagenary(14),day:sexagenary(34),hour:sexagenary(54)},luck:sexagenary(20),annual:sexagenary(42),sex:"male",luckDirection:"forward"});expect(result.ok).toBe(true);if(!result.ok)return;expect(result.value.topicCertificate.program).toEqual({total:37_231,executable:4_118,deferred:7_785,contested:41,evidence:22_107,fixture:3_180});expect(result.value.topicCertificate.evaluated).toBeGreaterThan(0);expect(result.value.topicCertificate.activated+result.value.topicCertificate.inactive+result.value.topicCertificate.unresolved).toBe(result.value.topicCertificate.evaluated)});
});
